import type { NextPage } from 'next'
import Link from 'next/link'
import Head from 'next/head'
import Image from 'next/image'
import Footer from '../components/Footer'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.home}>
        <nav className={styles.nav}>
          <div className={styles.container}>
            <div className={styles.logo}>
              Logo
            </div>
            <ul className={styles.links}>
              <li>
                <Link href={"/Login"}>
                  <a>Login</a>
                </Link>
              </li>
              <li>
                <Link href={"/Register"}>
                  <a>Register</a>
                </Link>
              </li>
            </ul>
          </div>
        </nav>
      </main>

      <Footer />
    </>
  )
}

export default Home
